[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.118.2",
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "scipy>=1.16.2",
    "uvicorn>=0.37.0",
    "slowapi>=0.1.9",
]
